#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WeatherForecast.Resource", IsApplication=true)]

namespace WeatherForecast
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public const int indicatorColor = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int indicatorName = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int maxHeight = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int maxWidth = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int minHeight = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int minWidth = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060002
			public const int primaryDark = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int primaryLight = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int primaryMain = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int primaryText = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int primaryWhite = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int transparent = 2131099653;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cardShape = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int circle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int autocompleteView = 2131165186;
			
			// aapt resource value: 0x7f070013
			public const int cityHeader = 2131165203;
			
			// aapt resource value: 0x7f070009
			public const int cloudinessHeader = 2131165193;
			
			// aapt resource value: 0x7f070011
			public const int currentTemperture = 2131165201;
			
			// aapt resource value: 0x7f070008
			public const int graphFragmentContainer = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int graphView = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int humidityHeader = 2131165194;
			
			// aapt resource value: 0x7f070010
			public const int imageView1 = 2131165200;
			
			// aapt resource value: 0x7f070004
			public const int indicator = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int loadingNextButton = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int mainWindow = 2131165189;
			
			// aapt resource value: 0x7f070014
			public const int openMap = 2131165204;
			
			// aapt resource value: 0x7f07000b
			public const int pressureHeader = 2131165195;
			
			// aapt resource value: 0x7f070012
			public const int rangeTemperture = 2131165202;
			
			// aapt resource value: 0x7f070001
			public const int searchBox = 2131165185;
			
			// aapt resource value: 0x7f07000e
			public const int sunriseHeader = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int sunsetHeader = 2131165199;
			
			// aapt resource value: 0x7f070007
			public const int todayDetailFragmentContainer = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int todayFragmentContainer = 2131165190;
			
			// aapt resource value: 0x7f07000d
			public const int windDirectionHeader = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int windSpeedHeader = 2131165196;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int graphDailyFragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int loading = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loadingDialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int mainWindow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int todayDetailsFragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int todayFragment = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AVLoadingIndicatorView = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AVLoadingIndicatorView_Large = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int AVLoadingIndicatorView_Small = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int NoActionBar = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AVLoadingIndicatorView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 5
			public const int AVLoadingIndicatorView_indicatorColor = 5;
			
			// aapt resource value: 4
			public const int AVLoadingIndicatorView_indicatorName = 4;
			
			// aapt resource value: 3
			public const int AVLoadingIndicatorView_maxHeight = 3;
			
			// aapt resource value: 1
			public const int AVLoadingIndicatorView_maxWidth = 1;
			
			// aapt resource value: 2
			public const int AVLoadingIndicatorView_minHeight = 2;
			
			// aapt resource value: 0
			public const int AVLoadingIndicatorView_minWidth = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
